"use strict";
let two = 2;
let array = ["hey", "hello", "hi"];
array[1] = 1;
console.log(array);
let result = 3;
result = 4;
result = "hey";
let person;
person = { name: "Johannes", location: "Niederrhein", isProgrammer: true };
